spring:
  application:
    name: hello-spring-cloud-config

  zipkin:
    base-url: http://localhost:9411


  cloud:
    config:
      label: master
      server:
        git:
          uri: http://192.168.31.6/root/spring-cloud-config.git
          search-paths: respo
          username: root
          password: root123456
          #http://localhost:8888/web-admin-feign/master
  boot:
    admin:
      client:
        url: http://localhost:8084


server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/